export {default as MainContainer} from './MainContainer';
export {default as USer } from './User';
export {default as Followers} from './Followers';
export {default as Lang } from './Lang';
export {default as Stars} from './Stars';
export {default as Forked} from './Forked';
export {default as StarLang} from './starLang';
export {default as Login} from './Login';
export {default as PriveRoute} from './PriveRouter';
export {default as Error} from './Error';
export {default as Loading} from './Loading';
export {default as Alert} from './Alert';